import test from 'node:test';
import assert from 'node:assert/strict';
import { RaceEngineer } from './intelligence.js';
import { initialState } from './state.js';

function race(){const s=initialState();s.status='CONNECTED';s.sessionUid='test';s.sessionLinkId=1;s.sessionType='Race';s.context.category='RACE';s.player.position=2;s.player.driver='PLAYER';s.player.fuel=30;s.player.fuelRemainingLaps=2;s.player.ers=60;s.drivers=[{position:1,name:'AHEAD',team:'Ferrari',lap:3,sector:1,gap:'LEADER',interval:'—',tyre:'MEDIUM',tyreAge:8,pit:false},{position:2,name:'PLAYER',team:'Alpine',lap:3,sector:1,gap:'+0.800',interval:'+0.800',tyre:'SOFT',tyreAge:2,pit:false},{position:3,name:'BEHIND',team:'McLaren',lap:3,sector:1,gap:'+2.600',interval:'+1.800',tyre:'HARD',tyreAge:10,pit:false}];return s}

test('does not announce an obvious DRS gap when monitoring starts',()=>{const engineer=new RaceEngineer(),state=race();assert.equal(engineer.analyze(state,1000).engineer.primary,null);assert.equal(engineer.analyze(state,5000).engineer.primary,null)});
test('announces DRS only when the same rival crosses into range',()=>{const engineer=new RaceEngineer(),state=race();state.drivers[1].interval='+1.400';engineer.analyze(state,1000);state.drivers[1].interval='+0.900';const result=engineer.analyze(state,2000);assert.match(result.engineer.primary?.id??'',/^drs-attack-/);assert.equal(result.engineer.primary?.priority,'opportunity')});
test('does not repeat the same DRS call after its cooldown starts',()=>{const engineer=new RaceEngineer(),state=race();state.drivers[1].interval='+1.400';engineer.analyze(state,1000);state.drivers[1].interval='+0.900';engineer.analyze(state,2000);engineer.analyze(state,12000);state.drivers[1].interval='+1.400';engineer.analyze(state,13000);state.drivers[1].interval='+0.900';assert.equal(engineer.analyze(state,14000).engineer.primary,null)});
test('predicts a multi-lap catch from the strategy trend',()=>{const state=race();state.totalLaps=20;state.lap=5;state.strategy.ahead={name:'AHEAD',position:1,gap:2,rate:-.5,direction:'GAINING',laps:4,catchLaps:4,tyre:'MEDIUM',tyreAge:8,pit:false};const result=new RaceEngineer().analyze(state,1000);assert.match(result.engineer.primary?.id??'',/^prediction-ahead-/);assert.match(result.engineer.primary?.title??'',/4 LAPS/)});
test('tyre wear alone is not reported as structural car damage',()=>{const state=race();state.context.damage.tyres=45;assert.equal(new RaceEngineer().analyze(state,1000).engineer.primary,null)});
test('critical damage overrides an attack opportunity',()=>{const state=race();state.context.damage.frontWing=72;const result=new RaceEngineer().analyze(state);assert.equal(result.engineer.primary?.id,'severe-damage');assert.equal(result.engineer.primary?.priority,'critical')});
test('safety messages override a strategy call',()=>{const state=race(),now=1000;state.flag='RED';state.strategy.recommendation={id:'strategy-undercut',priority:'opportunity',title:'UNDERCUT AVAILABLE',evidence:'Three clean laps support the call.',action:'Box before the car ahead.',confidence:94,createdAt:now,expiresAt:now+12000};const result=new RaceEngineer().analyze(state,now);assert.equal(result.engineer.primary?.id,'red-flag');assert.equal(result.engineer.primary?.priority,'critical')});
