import { initialState } from './state.js';
import type { DriverState, RaceState, WeatherForecast } from './types.js';

const tracks:Record<number,string>={0:'Melbourne',1:'Paul Ricard',2:'Shanghai',3:'Bahrain',4:'Catalunya',5:'Monaco',6:'Montreal',7:'Silverstone',8:'Hockenheim',9:'Hungaroring',10:'Spa',11:'Monza',12:'Singapore',13:'Suzuka',14:'Abu Dhabi',15:'Texas',16:'Brazil',17:'Austria',18:'Sochi',19:'Mexico',20:'Baku',21:'Sakhir Short',22:'Silverstone Short',26:'Zandvoort',27:'Imola',29:'Miami',30:'Las Vegas',31:'Losail',32:'Jeddah'};
const weatherName=(value:number)=>['Clear','Light cloud','Overcast','Light rain','Heavy rain','Storm'][value]||'Unknown';
const tyreName=(compound:number)=>({16:'SOFT',17:'MEDIUM',18:'HARD',7:'INTER',8:'WET'}[compound]||'—') as DriverState['tyre'];
const teamName=(id:number)=>({0:'Mercedes',1:'Ferrari',2:'Red Bull',3:'Williams',4:'Aston Martin',5:'Alpine',6:'RB',7:'Haas',8:'McLaren',9:'Sauber'}[id]||`Team ${id}`);
const sessions:Record<number,[string,RaceState['context']['category']]>= {0:['Unknown','UNKNOWN'],1:['Practice 1','PRACTICE'],2:['Practice 2','PRACTICE'],3:['Practice 3','PRACTICE'],4:['Short Practice','PRACTICE'],5:['Qualifying 1','QUALIFYING'],6:['Qualifying 2','QUALIFYING'],7:['Qualifying 3','QUALIFYING'],8:['Short Qualifying','QUALIFYING'],9:['One-Shot Qualifying','QUALIFYING'],10:['Sprint Shootout 1','SPRINT'],11:['Sprint Shootout 2','SPRINT'],12:['Sprint Shootout 3','SPRINT'],13:['Short Sprint Shootout','SPRINT'],14:['One-Shot Sprint Shootout','SPRINT'],15:['Race','RACE'],16:['Race 2','RACE'],17:['Race 3','RACE'],18:['Time Trial','TIME_TRIAL']};

function freshConnected(sessionUid:string,sessionTime:number,packetCount=0):RaceState {
  return {...initialState(),status:'CONNECTED',sessionUid,sessionTime,updatedAt:Date.now(),packetCount};
}

export function packetEventCode(buffer:Buffer):string|null {
  return buffer.length>=33&&buffer.readUInt8(6)===3?buffer.subarray(29,33).toString('ascii'):null;
}

export function parsePacket(buffer:Buffer,state:RaceState):RaceState|null {
  if(buffer.length<29)return null;
  const format=buffer.readUInt16LE(0);
  if(format<2024||format>2026)return null;
  const packetId=buffer.readUInt8(6),player=buffer.readUInt8(27),base=29,now=Date.now();
  const sessionUid=buffer.readBigUInt64LE(7).toString(),sessionTime=buffer.readFloatLE(15);
  const source=state.sessionUid&&state.sessionUid!==sessionUid?freshConnected(sessionUid,sessionTime):state;
  const packetStatus=format===2026&&source.context.category==='UNKNOWN'?'WAITING' as const:'CONNECTED' as const;
  const next={...source,status:packetStatus,sessionUid,sessionTime,updatedAt:now,packetCount:source.packetCount+1};
  try {
    if(format===2026)return parse2026(buffer,next,packetId,player,base);
    if(packetId===1&&buffer.length>base+14){const paused=!!buffer.readUInt8(base+14);return {...next,status:paused?'PAUSED':'CONNECTED',weather:weatherName(buffer.readUInt8(base)),totalLaps:buffer.readUInt8(base+3),track:tracks[buffer.readInt8(base+6)]||`Track ${buffer.readInt8(base+6)}`,context:{...next.context,gamePaused:paused}};}
    if(packetId===2){const size=57,o=base+player*size;if(buffer.length>o+54){const last=buffer.readUInt32LE(o),pos=buffer.readUInt8(o+24),lap=buffer.readUInt8(o+25),lapDistance=buffer.readFloatLE(o+20),drivers=next.drivers.map((d,i)=>{const x=base+i*size;if(buffer.length<x+29)return d;return {...d,position:buffer.readUInt8(x+24),lap:buffer.readUInt8(x+25),sector:buffer.readUInt8(x+28)+1,pit:buffer.readUInt8(x+26)>0}}).sort((a,b)=>a.position-b.position);return {...next,lap,drivers,player:{...next.player,position:pos,lapDistance:Number.isFinite(lapDistance)?lapDistance:next.player.lapDistance,lastLap:last?formatMs(last):next.player.lastLap}};}}
    if(packetId===4&&buffer.length>base){const count=Math.min(22,buffer.readUInt8(base)),size=58,existing=next.drivers,drivers=Array.from({length:count},(_,i)=>{const o=base+1+i*size,name=buffer.subarray(o+7,o+55).toString('utf8').replace(/\0/g,'').trim()||`DRIVER ${i+1}`,old=existing[i];return {vehicleIndex:i,position:old?.position||i+1,name,team:teamName(buffer.readUInt8(o+3)),lap:old?.lap||next.lap,sector:old?.sector||1,gap:old?.gap||(i?'—':'LEADER'),interval:old?.interval||'—',tyre:old?.tyre||'—',tyreAge:old?.tyreAge||0,pit:old?.pit||false};}),me=drivers[player];return {...next,drivers,player:{...next.player,driver:me?.name||next.player.driver,team:me?.team||next.player.team}};}
    if(packetId===6){const size=60,o=base+player*size;if(buffer.length>o+52)return {...next,player:{...next.player,speed:buffer.readUInt16LE(o),throttle:Math.round(buffer.readFloatLE(o+2)*100),steer:Math.round(buffer.readFloatLE(o+6)*1000)/1000,brake:Math.round(buffer.readFloatLE(o+10)*100),gear:buffer.readInt8(o+15),rpm:buffer.readUInt16LE(o+16),drs:!!buffer.readUInt8(o+18),brakeTemps:[0,1,2,3].map(i=>buffer.readUInt16LE(o+20+i*2)),tyreTemps:[0,1,2,3].map(i=>buffer.readUInt8(o+28+i))}};}
    if(packetId===7){const size=55,o=base+player*size;if(buffer.length>o+54)return {...next,player:{...next.player,fuel:buffer.readFloatLE(o+5),fuelRemainingLaps:buffer.readFloatLE(o+13),ers:Math.round(buffer.readFloatLE(o+21)/40000),tyre:tyreName(buffer.readUInt8(o+29))}};}
    return next;
  } catch { return null; }
}

function parse2026(buffer:Buffer,next:RaceState,packetId:number,player:number,base:number):RaceState {
  if(packetId===1&&buffer.length===926){
    const sessionCode=buffer.readUInt8(base+6),session=sessions[sessionCode]||sessions[0],sessionLinkId=buffer.readUInt32LE(base+649),phaseChanged=next.context.category!=='UNKNOWN'&&(next.sessionLinkId!==sessionLinkId||next.sessionType!==session[0]),current=phaseChanged?freshConnected(next.sessionUid,next.sessionTime,1):next;
    const paused=!!buffer.readUInt8(base+14),forecastCount=Math.min(64,buffer.readUInt8(base+126)),weatherForecast:WeatherForecast[]=[];
    for(let i=0;i<forecastCount;i++){const o=base+127+i*8,sampleSession=buffer.readUInt8(o);if(sampleSession!==sessionCode&&sampleSession!==0)continue;weatherForecast.push({minutes:buffer.readUInt8(o+1),weather:weatherName(buffer.readUInt8(o+2)),trackTemperature:buffer.readInt8(o+3),airTemperature:buffer.readInt8(o+5),rainPercentage:buffer.readUInt8(o+7)});}
    const sc=buffer.readUInt8(base+124),trackId=buffer.readInt8(base+7);
    return {...current,status:paused?'PAUSED':'CONNECTED',sessionLinkId,sessionType:session[0],weather:weatherName(buffer.readUInt8(base)),totalLaps:buffer.readUInt8(base+3),track:tracks[trackId]||`Track ${trackId}`,safetyCar:sc===1?'FULL':sc===2?'VSC':'NONE',context:{...current.context,category:session[1],timeLeft:buffer.readUInt16LE(base+9),trackLength:buffer.readUInt16LE(base+4),trackTemp:buffer.readInt8(base+1),airTemp:buffer.readInt8(base+2),gamePaused:paused,weatherForecast,pitWindowIdeal:buffer.readUInt8(base+653),pitWindowLatest:buffer.readUInt8(base+654),pitRejoinPosition:buffer.readUInt8(base+655)}};
  }
  if(packetId===4&&buffer.length===1470){const count=Math.min(24,buffer.readUInt8(base)),size=60,old=next.drivers,drivers=Array.from({length:count},(_,i)=>{const o=base+1+i*size,name=buffer.subarray(o+10,o+42).toString('utf8').replace(/\0/g,'').trim()||`DRIVER ${i+1}`,previous=old.find(d=>(d.vehicleIndex??-1)===i)||old.find(d=>d.name===name);return {vehicleIndex:i,position:previous?.position||i+1,name,team:teamName(buffer.readUInt16LE(o+5)),lap:previous?.lap||next.lap,sector:previous?.sector||1,gap:previous?.gap||(i?'—':'LEADER'),interval:previous?.interval||'—',bestLap:previous?.bestLap,tyre:previous?.tyre||'—',tyreAge:previous?.tyreAge||0,pit:previous?.pit||false,driverStatus:previous?.driverStatus||0};}),me=drivers[player];return {...next,drivers,player:{...next.player,driver:me?.name||next.player.driver,team:me?.team||next.player.team}};}
  if(packetId===2&&buffer.length===1399){
    const size=57,drivers=next.drivers.map((d,i)=>{const o=base+i*size;if(o+56>=buffer.length)return d;const gapLeader=buffer.readUInt16LE(o+17)+buffer.readUInt8(o+19)*60000,rawInterval=buffer.readUInt16LE(o+14)+buffer.readUInt8(o+16)*60000,pos=buffer.readUInt8(o+32),last=buffer.readUInt32LE(o),s1=buffer.readUInt16LE(o+8)+buffer.readUInt8(o+10)*60000,s2=buffer.readUInt16LE(o+11)+buffer.readUInt8(o+13)*60000,validGap=pos===1||(gapLeader>0&&gapLeader<600000),validInterval=pos===1||(rawInterval>0&&rawInterval<120000&&(!validGap||rawInterval<=gapLeader+2000)),samePosition=d.position===pos,gap=pos===1?'LEADER':validGap?formatGap(gapLeader):samePosition?d.gap:'—',interval=pos===1?'—':validInterval?formatGap(rawInterval):samePosition?d.interval:'—',s3=last&&s1&&s2&&last>s1+s2?last-s1-s2:0;return {...d,position:pos,lap:buffer.readUInt8(o+33),sector:buffer.readUInt8(o+36)+1,pit:buffer.readUInt8(o+34)>0,driverStatus:buffer.readUInt8(o+44),gap,interval,gapStale:pos!==1&&!validGap&&gap!=='—',intervalStale:pos!==1&&!validInterval&&interval!=='—',lastLap:last?formatMs(last):d.lastLap,sector1:s1?formatMs(s1):d.sector1||'—',sector2:s2?formatMs(s2):d.sector2||'—',sector3:s3?formatMs(s3):d.sector3||'—'};});
    const o=base+player*size,last=buffer.readUInt32LE(o),pos=buffer.readUInt8(o+32),rawLap=buffer.readUInt8(o+33),lap=next.totalLaps?Math.min(rawLap,next.totalLaps):rawLap,s1=buffer.readUInt16LE(o+8)+buffer.readUInt8(o+10)*60000,s2=buffer.readUInt16LE(o+11)+buffer.readUInt8(o+13)*60000,invalid=!!buffer.readUInt8(o+37),penalties=buffer.readUInt8(o+38),warnings=buffer.readUInt8(o+39),lapDistance=buffer.readFloatLE(o+20),pit=buffer.readUInt8(o+34)>0,driverStatus=buffer.readUInt8(o+44);
    let alerts=next.alerts;if(invalid&&!next.context.lapInvalid)alerts=addAlert(alerts,`invalid-${lap}`,'warning','Lap invalidated','Track limits or session rules invalidated the current lap.');if(penalties>next.context.penalties)alerts=addAlert(alerts,`penalty-${penalties}-${lap}`,'critical',`${penalties}s penalty`,`Race control added a penalty. Total is now ${penalties} seconds.`);if(warnings>next.context.warnings)alerts=addAlert(alerts,`warning-${warnings}-${lap}`,'warning','Race control warning',`${warnings} warning${warnings===1?'':'s'} accumulated.`);
    const terminal=['FINISHED','RETIRED'].includes(next.context.lifecycle),race=['RACE','SPRINT'].includes(next.context.category),lifecycle=terminal?next.context.lifecycle:race&&next.totalLaps&&lap>=next.totalLaps?'FINAL_LAP':race&&lap>0?'ACTIVE':next.context.lifecycle;
    return {...next,lap,drivers,alerts,context:{...next.context,lifecycle,currentLapTime:formatMs(buffer.readUInt32LE(o+4)),sector1:s1?formatMs(s1):'—',sector2:s2?formatMs(s2):'—',lapInvalid:invalid,penalties,warnings,gridPosition:buffer.readUInt8(o+43)},player:{...next.player,position:pos,lapDistance:Number.isFinite(lapDistance)?lapDistance:next.player.lapDistance,pit,driverStatus,lastLap:last?formatMs(last):next.player.lastLap}};
  }
  if(packetId===6&&buffer.length===1448){const size=59,o=base+player*size;return {...next,player:{...next.player,speed:buffer.readUInt16LE(o),throttle:Math.round(buffer.readFloatLE(o+2)*100),steer:Math.round(buffer.readFloatLE(o+6)*1000)/1000,brake:Math.round(buffer.readFloatLE(o+10)*100),gear:buffer.readInt8(o+15),rpm:buffer.readUInt16LE(o+16),drs:!!buffer.readUInt8(o+18),brakeTemps:[2,3,0,1].map(i=>buffer.readUInt16LE(o+22+i*2)),tyreTemps:[2,3,0,1].map(i=>buffer.readUInt8(o+30+i))}};}
  if(packetId===7&&buffer.length===1445){const size=59,o=base+player*size,visual=buffer.readUInt8(o+26),age=buffer.readUInt8(o+27),ers=Math.max(0,Math.min(100,Math.round(buffer.readFloatLE(o+37)/40000))),fiaFlag=buffer.readInt8(o+28),tyre=tyreName(visual),drivers=next.drivers.map((d,i)=>{const x=base+i*size;return {...d,tyre:tyreName(buffer.readUInt8(x+26)),tyreAge:buffer.readUInt8(x+27)}}),flag=next.flag==='RED'||next.flag==='CHEQUERED'?next.flag:fiaFlag===3?'YELLOW':'GREEN';return {...next,flag,drivers,player:{...next.player,fuel:buffer.readFloatLE(o+5),fuelRemainingLaps:buffer.readFloatLE(o+13),ers,tyre,tyreAge:age}};}
  if(packetId===10&&buffer.length===1133){const size=46,o=base+player*size,tyreWear=[2,3,0,1].map(i=>Math.round(buffer.readFloatLE(o+i*4))),damage={frontWing:Math.max(buffer.readUInt8(o+28),buffer.readUInt8(o+29)),rearWing:buffer.readUInt8(o+30),floor:buffer.readUInt8(o+31),diffuser:buffer.readUInt8(o+32),sidepod:buffer.readUInt8(o+33),gearbox:buffer.readUInt8(o+36),engine:buffer.readUInt8(o+37),tyres:Math.max(...[16,17,18,19].map(i=>buffer.readUInt8(o+i))),brakes:Math.max(...[20,21,22,23].map(i=>buffer.readUInt8(o+i)))},alerts=damageAlerts(next.context.damage,damage,next.alerts,next.lap),body=Math.max(damage.rearWing,damage.floor,damage.diffuser,damage.sidepod);return {...next,alerts,context:{...next.context,tyreWear,damage},player:{...next.player,frontWing:Math.max(0,100-damage.frontWing),damage:body}};}
  if(packetId===11&&buffer.length===1460){const car=buffer.readUInt8(base),bestLapNumber=buffer.readUInt8(base+3);if(!bestLapNumber)return next;const o=base+7+(bestLapNumber-1)*14;if(o+13>=buffer.length)return next;const best=formatMs(buffer.readUInt32LE(o)),drivers=next.drivers.map((d,i)=>(d.vehicleIndex??i)===car?{...d,bestLap:best}:d);return {...next,drivers,player:car===player?{...next.player,bestLap:best}:next.player};}
  if(packetId===3&&buffer.length>=33){
    const code=packetEventCode(buffer);
    if(code==='RDFL')return {...next,flag:'RED',alerts:addAlert(next.alerts,`red-${next.lap}`,'critical','Red flag','Session stopped — return safely to the pits.')};
    if(code==='CHQF')return {...next,flag:'CHEQUERED',context:{...next.context,lifecycle:'FINAL_LAP'},alerts:addAlert(next.alerts,'chequered','info','Chequered flag','Complete the final lap.')};
    if(code==='SEND')return {...next,status:'PAUSED',flag:['RACE','SPRINT'].includes(next.context.category)?'CHEQUERED':next.flag,context:{...next.context,lifecycle:'FINISHED'}};
    if(code==='SCAR'){const kind=buffer.readUInt8(base+4),label=kind===1?'Safety Car deployed':kind===2?'Virtual Safety Car deployed':'Safety Car ending';return {...next,safetyCar:kind===1?'FULL':kind===2?'VSC':'NONE',alerts:addAlert(next.alerts,`sc-${kind}-${next.lap}`,'warning',label,'Observe delta and overtaking restrictions.')}}
    if(code==='COLL'&&buffer.length>=35){
      const first=buffer.readUInt8(base+4),second=buffer.readUInt8(base+5),names=[driverName(next,first),driverName(next,second)],incident=raceIncident(next,'COLLISION',[first,second],`${names[0]} / ${names[1]}`,`Collision on lap ${next.lap}.`,'warning');
      return {...next,context:{...next.context,incidents:addIncident(next.context.incidents,incident)},alerts:addAlert(next.alerts,incident.id,'warning','Collision',`${names[0]} and ${names[1]} made contact.`)};
    }
    if(code==='RTMT'&&buffer.length>=34){
      const vehicle=buffer.readUInt8(base+4),name=driverName(next,vehicle),incident=raceIncident(next,'RETIREMENT',[vehicle],name,`${name} retired on lap ${next.lap}.`,'info'),playerRetired=vehicle===player;
      return {...next,context:{...next.context,lifecycle:playerRetired?'RETIRED':next.context.lifecycle,incidents:addIncident(next.context.incidents,incident)},alerts:addAlert(next.alerts,incident.id,playerRetired?'critical':'info',playerRetired?'Retired':`${name} retired`,playerRetired?'Your race has ended.':'Race order may change.')};
    }
    if(code==='OVTK'&&buffer.length>=35){
      const overtaking=buffer.readUInt8(base+4),overtaken=buffer.readUInt8(base+5),incident=raceIncident(next,'OVERTAKE',[overtaking,overtaken],`${driverName(next,overtaking)} passed ${driverName(next,overtaken)}`,'Race order changed.','info');
      return {...next,context:{...next.context,incidents:addIncident(next.context.incidents,incident)}};
    }
    if(code==='FTLP'&&buffer.length>=38){
      const vehicle=buffer.readUInt8(base+4),time=buffer.readFloatLE(base+5),name=driverName(next,vehicle),incident=raceIncident(next,'FASTEST_LAP',[vehicle],`Fastest lap · ${name}`,Number.isFinite(time)?`${time.toFixed(3)} seconds.`:'Fastest lap recorded.','info');
      return {...next,context:{...next.context,incidents:addIncident(next.context.incidents,incident)}};
    }
  }
  return next;
}

function formatMs(ms:number){if(!ms)return '—';const m=Math.floor(ms/60000),s=(ms%60000/1000).toFixed(3).padStart(6,'0');return `${m}:${s}`;}
function formatGap(ms:number){return ms>0&&ms<600000?`+${(ms/1000).toFixed(3)}`:'—';}
function addAlert(existing:RaceState['alerts'],id:string,level:'info'|'warning'|'critical',title:string,detail:string){return [{id,level,title,detail,timestamp:Date.now()},...existing.filter(a=>a.id!==id)].slice(0,12);}
function driverName(state:RaceState,vehicleIndex:number){return state.drivers.find((driver,index)=>(driver.vehicleIndex??index)===vehicleIndex)?.name||`Car ${vehicleIndex+1}`;}
function raceIncident(state:RaceState,kind:RaceState['context']['incidents'][number]['kind'],vehicleIndices:number[],title:string,detail:string,severity:RaceState['context']['incidents'][number]['severity']){return {id:`${kind.toLowerCase()}-${state.lap}-${state.sessionTime.toFixed(3)}-${vehicleIndices.join('-')}`,kind,lap:state.lap,at:Date.now(),vehicleIndices,title,detail,severity};}
function addIncident(existing:RaceState['context']['incidents']|undefined,incident:RaceState['context']['incidents'][number]){return [incident,...(existing??[]).filter(item=>item.id!==incident.id)].slice(0,20);}
function damageAlerts(previous:RaceState['context']['damage'],current:RaceState['context']['damage'],existing:RaceState['alerts'],lap:number){const labels:Record<keyof typeof current,string>={frontWing:'Front wing',rearWing:'Rear wing',floor:'Floor',diffuser:'Diffuser',sidepod:'Sidepods',gearbox:'Gearbox',engine:'Engine',tyres:'Tyres',brakes:'Brakes'},threshold=(value:number)=>value>=90?90:value>=60?60:value>=30?30:value>=10?10:0;let alerts=existing;for(const key of Object.keys(current) as (keyof typeof current)[]){const level=threshold(current[key]);if(level>threshold(previous[key]))alerts=addAlert(alerts,`damage-${key}-${level}-${lap}`,level>=60?'critical':'warning',`${labels[key]} damage · ${current[key]}%`,level>=60?'Severe damage — consider pitting immediately.':'Damage detected — monitor handling and lap time.');}return alerts;}
