import type { RaceState } from './types.js';

const names = ['VERSTAPPEN','NORRIS','LECLERC','PIASTRI','RUSSELL','SAINZ','HAMILTON','ALONSO','ANTONELLI','GASLY'];
const teams = ['Red Bull','McLaren','Ferrari','McLaren','Mercedes','Williams','Ferrari','Aston Martin','Mercedes','Alpine'];
const tyres = ['MEDIUM','MEDIUM','SOFT','HARD','MEDIUM','SOFT','HARD','MEDIUM','SOFT','HARD'] as const;
const emptyStrategy=():RaceState['strategy']=>({status:'LEARNING',ahead:null,behind:null,gapHistory:[],stint:{compound:'—',age:0,cleanLaps:0,averageLapMs:null,degradationMs:null,paceDeltaMs:null,wear:0},pitLossSeconds:null,rejoinPosition:0,plan:{status:'LEARNING',pitLossSeconds:22,pitLossSource:'TRACK_ESTIMATE',traffic:'UNKNOWN',rejoinPosition:0,rejoinMin:0,rejoinMax:0,rejoinRival:'',horizonLaps:0,freshTyreGainSeconds:null,stayOneMoreCostSeconds:null,undercutGainSeconds:null,overcutGainSeconds:null,confidence:0},rules:{mandatoryStopRequired:false,mandatoryStopComplete:true,compoundsUsed:[],stops:0,windowStart:null,recommendedPitLap:null,windowEnd:null,latestSafePitLap:null},raceMode:'LEARNING',modeReason:'Waiting for race data',targetLapTime:'—',targetLapDeltaMs:null,lastStop:null,decisions:[],recommendation:null});
export function initialState():RaceState {
  return {status:'WAITING',sessionUid:'',sessionLinkId:0,sessionTime:0,sessionType:'Unknown',track:'Waiting for F1 25',weather:'—',lap:0,totalLaps:0,safetyCar:'NONE',flag:'GREEN',context:{category:'UNKNOWN',timeLeft:0,trackLength:0,trackTemp:0,airTemp:0,gamePaused:false,weatherForecast:[],pitWindowIdeal:0,pitWindowLatest:0,pitRejoinPosition:0,currentLapTime:'—',sector1:'—',sector2:'—',lapInvalid:false,penalties:0,warnings:0,gridPosition:0,tyreWear:[0,0,0,0],damage:{frontWing:0,rearWing:0,floor:0,diffuser:0,sidepod:0,gearbox:0,engine:0,tyres:0,brakes:0}},
    player:{position:1,driver:'PLAYER',team:'—',speed:0,gear:0,rpm:0,throttle:0,brake:0,steer:0,lapDistance:0,drs:false,fuel:0,fuelRemainingLaps:0,ers:0,tyre:'—',tyreAge:0,tyreTemps:[0,0,0,0],brakeTemps:[0,0,0,0],frontWing:0,damage:0,pit:false,driverStatus:0,lastLap:'—',bestLap:'—'},drivers:[],alerts:[],engineer:{primary:null,secondary:[],log:[]},coach:{status:'LEARNING',lapsLearned:0,cornersLearned:0,message:null,analysis:{currentLap:0,referenceLap:null,referenceLapTime:'—',current:[],reference:[],corners:[],insights:[],quality:{invalid:false,pit:false,unsafe:false}}},strategy:emptyStrategy(),updatedAt:Date.now(),packetCount:0};
}
export function demoState(tick:number, previous:RaceState, category:'RACE'|'PRACTICE'|'QUALIFYING'='RACE'):RaceState {
  const lap = 12 + Math.floor(tick/40); const phase=tick%40; const speed=Math.round(248+62*Math.sin(tick/3));
  const position = tick>85 ? 2 : 3; const flag = tick%90>70&&tick%90<78?'YELLOW':'GREEN';
  const drivers=names.map((name,i)=>({position:i+1,name:i===position-1?'D. DELLA':name,team:i===position-1?'McLaren':teams[i],lap,sector:(Math.floor(phase/14)%3)+1,gap:i===0?'LEADER':`+${(i*1.483+Math.sin(tick/8+i)*.3).toFixed(3)}`,interval:i===0?'—':`+${(1.1+Math.abs(Math.sin(i))*1.4).toFixed(3)}`,lastLap:`1:${(34+i*.31).toFixed(3).padStart(6,'0')}`,bestLap:`1:${(33+i*.27).toFixed(3).padStart(6,'0')}`,sector1:'0:30.221',sector2:'0:31.408',sector3:'0:33.277',tyre:i===position-1?'MEDIUM' as const:tyres[i],tyreAge:i===position-1?lap-5:7+i,pit:false}));
  const alerts=[...previous.alerts];
  const add=(key:string,title:string,detail:string,level:'info'|'warning'|'critical')=>{if(!alerts.some(a=>a.id===`${lap}-${key}`)) alerts.unshift({id:`${lap}-${key}`,title,detail,level,timestamp:Date.now()});};
  if(phase===8)add('drs','DRS available','Detection point cleared — gap 0.8s','info');
  if(flag==='YELLOW'&&previous.flag!=='YELLOW')add('yellow','Yellow flag — Sector 2','Reduce speed, no overtaking','warning');
  if(lap>=14&&phase===20)add('tyres','Tyre wear increasing','Front-left estimated at 54% wear','warning');
  const sessionType=category==='RACE'?'Race':category==='PRACTICE'?'Practice 1':'Qualifying 1';
  return {...previous,status:'DEMO',sessionUid:'demo',sessionLinkId:category==='RACE'?1:category==='PRACTICE'?2:3,sessionTime:tick/2,sessionType,track:'Bahrain International Circuit',weather:'Dry · 29°C',lap,totalLaps:category==='RACE'?57:0,flag,safetyCar:category==='RACE'&&flag==='YELLOW'?'VSC':'NONE',context:{...previous.context,category,timeLeft:Math.max(0,1800-tick),trackLength:5412,trackTemp:38,airTemp:29,gamePaused:false,weatherForecast:[{minutes:5,weather:'Clear',rainPercentage:0,trackTemperature:38,airTemperature:29}],pitWindowIdeal:20,pitWindowLatest:24,pitRejoinPosition:8,currentLapTime:`1:${(20+phase*1.8).toFixed(3).padStart(6,'0')}`,sector1:'0:30.221',sector2:'0:31.408',lapInvalid:false,penalties:0,warnings:1,gridPosition:5,tyreWear:[31,29,25,24],damage:{frontWing:phase>32?8:0,rearWing:0,floor:0,diffuser:0,sidepod:0,gearbox:0,engine:0,tyres:0,brakes:0}},updatedAt:Date.now(),packetCount:previous.packetCount+1,
    player:{position,driver:'D. DELLA',team:'McLaren',speed,gear:speed<80?2:speed<140?4:speed<220?6:8,rpm:9200+Math.round(Math.sin(tick)*1800),throttle:Math.max(0,Math.round(82+18*Math.sin(tick/2))),brake:Math.max(0,Math.round(70*Math.cos(tick/2.3))),steer:Math.sin(tick/3)*.45,lapDistance:phase*125,drs:phase>9&&phase<24,fuel:58.4-lap*.72-phase*.018,fuelRemainingLaps:3.4,ers:Math.round(62+25*Math.sin(tick/7)),tyre:'MEDIUM',tyreAge:lap-5,tyreTemps:[93,91,89,90].map((v,i)=>v+Math.round(Math.sin(tick/4+i)*3)),brakeTemps:[612,598,570,585].map((v,i)=>v+Math.round(Math.sin(tick/3+i)*25)),frontWing:100,damage:phase>32?8:0,pit:false,driverStatus:4,lastLap:'1:35.842',bestLap:'1:34.906'},drivers,alerts:alerts.slice(0,8)};
}
