export type ConnectionStatus = 'WAITING' | 'CONNECTED' | 'PAUSED' | 'DEMO';
export interface WeatherForecast { minutes:number; weather:string; rainPercentage:number; trackTemperature:number; airTemperature:number }
export interface DriverState { vehicleIndex?:number; position:number; name:string; team:string; lap:number; sector:number; gap:string; interval:string; gapStale?:boolean; intervalStale?:boolean; lastLap?:string; bestLap?:string; sector1?:string; sector2?:string; sector3?:string; tyre:'SOFT'|'MEDIUM'|'HARD'|'INTER'|'WET'|'—'; tyreAge:number; pit:boolean; driverStatus?:number }
export interface RaceAlert { id:string; level:'info'|'warning'|'critical'; title:string; detail:string; timestamp:number }
export interface EngineerMessage { id:string; priority:'critical'|'action'|'opportunity'|'info'; title:string; evidence:string; action:string; confidence:number; createdAt:number; expiresAt:number }
export interface DecisionLogEntry { id:string; lap:number; at:number; status:'EMITTED'|'SUPPRESSED'|'RESOLVED'; reason:string }
export interface RivalTrend { vehicleIndex?:number; name:string; position:number; gap:number|null; rate:number|null; direction:'GAINING'|'LOSING'|'STABLE'|'LEARNING'; laps:number; catchLaps:number|null; tyre:string; tyreAge:number; pit:boolean }
export interface GapHistoryPoint { lap:number; ahead:number|null; behind:number|null }
export interface StintAnalysis { compound:string; age:number; cleanLaps:number; averageLapMs:number|null; degradationMs:number|null; paceDeltaMs:number|null; wear:number }
export type RaceMode='LEARNING'|'ATTACK'|'PUSH'|'MANAGE'|'DEFEND'|'BOX'|'SAFETY';
export interface PitPlan { status:'LEARNING'|'READY';pitLossSeconds:number;pitLossSource:'OBSERVED'|'TRACK_ESTIMATE';traffic:'CLEAR'|'MODERATE'|'HEAVY'|'UNKNOWN';rejoinPosition:number;rejoinMin:number;rejoinMax:number;rejoinRival:string;horizonLaps:number;freshTyreGainSeconds:number|null;stayOneMoreCostSeconds:number|null;undercutGainSeconds:number|null;overcutGainSeconds:number|null;confidence:number }
export interface StrategyRules { mandatoryStopRequired:boolean;mandatoryStopComplete:boolean;compoundsUsed:string[];stops:number;windowStart:number|null;recommendedPitLap:number|null;windowEnd:number|null;latestSafePitLap:number|null }
export interface PitOutcome { pitLap:number;exitLap:number;entryPosition:number;exitPosition:number;predictedMin:number;predictedMax:number;actualLossSeconds:number|null;positionsRecovered:number;cycleComplete:boolean }
export interface StrategyState { status:'LEARNING'|'READY'; ahead:RivalTrend|null; behind:RivalTrend|null; gapHistory:GapHistoryPoint[]; stint:StintAnalysis; pitLossSeconds:number|null; rejoinPosition:number; plan:PitPlan; rules:StrategyRules; raceMode:RaceMode; modeReason:string; targetLapTime:string; targetLapDeltaMs:number|null; lastStop:PitOutcome|null; decisions:DecisionLogEntry[]; recommendation:EngineerMessage|null }
export interface LapTracePoint { distance:number; speed:number; throttle:number; brake:number }
export interface LapInsight { lap:number; turn:number; distance:number; title:string; evidence:string; action:string; score:number }
export interface LapAnalysis { currentLap:number; referenceLap:number|null; referenceLapTime:string; current:LapTracePoint[]; reference:LapTracePoint[]; corners:number[]; insights:LapInsight[]; quality:{invalid:boolean;pit:boolean;unsafe:boolean} }
export interface RaceState {
  status:ConnectionStatus; sessionUid:string; sessionLinkId:number; sessionTime:number; sessionType:string; track:string; weather:string; lap:number; totalLaps:number; safetyCar:'NONE'|'FULL'|'VSC'; flag:'GREEN'|'YELLOW'|'RED'|'CHEQUERED';
  context:{category:'PRACTICE'|'QUALIFYING'|'SPRINT'|'RACE'|'TIME_TRIAL'|'UNKNOWN';timeLeft:number;trackLength:number;trackTemp:number;airTemp:number;gamePaused:boolean;weatherForecast:WeatherForecast[];pitWindowIdeal:number;pitWindowLatest:number;pitRejoinPosition:number;currentLapTime:string;sector1:string;sector2:string;lapInvalid:boolean;penalties:number;warnings:number;gridPosition:number;tyreWear:number[];damage:{frontWing:number;rearWing:number;floor:number;diffuser:number;sidepod:number;gearbox:number;engine:number;tyres:number;brakes:number}};
  player:{position:number;driver:string;team:string;speed:number;gear:number;rpm:number;throttle:number;brake:number;steer:number;lapDistance:number;drs:boolean;fuel:number;fuelRemainingLaps:number;ers:number;tyre:string;tyreAge:number;tyreTemps:number[];brakeTemps:number[];frontWing:number;damage:number;pit:boolean;driverStatus:number;lastLap:string;bestLap:string};
  drivers:DriverState[]; alerts:RaceAlert[]; engineer:{primary:EngineerMessage|null;secondary:EngineerMessage[];log:DecisionLogEntry[]}; coach:{status:'LEARNING'|'ACTIVE';lapsLearned:number;cornersLearned:number;message:EngineerMessage|null;analysis:LapAnalysis}; strategy:StrategyState; updatedAt:number; packetCount:number;
}
export interface Settings { udpPort:number; demoMode:boolean; autoSave:boolean; demoSession:'RACE'|'PRACTICE'|'QUALIFYING' }
