import { NavLink, Navigate, Route, Routes } from 'react-router-dom';
import { Activity, Car, ChartNoAxesColumnIncreasing, Flag, Radio, Settings as SettingsIcon, Volume2, VolumeX } from 'lucide-react';
import { useRaceState } from './useRaceState';
import { useRaceRadio } from './useRaceRadio';
import { AnalysisPage, CarPage, RacePage, SettingsPage, TimingPage } from './pages-v25';

const nav=[['/','Pit Wall',Flag],['/timing','Timing',ChartNoAxesColumnIncreasing],['/car','Car',Car],['/analysis','Analysis',Activity],['/settings','Settings',SettingsIcon]] as const;
const contextName=(category:string)=>category==='PRACTICE'?'PRACTICE ENGINEERING':category==='QUALIFYING'?'QUALIFYING CONTROL':category==='TIME_TRIAL'?'LAP ANALYSIS':'RACE PIT WALL';

export function App(){
  const state=useRaceState(),radio=useRaceRadio(state),timed=!['RACE','SPRINT'].includes(state.context.category),age=state.telemetry.ageMs;
  const statusLabel=state.status==='DEMO'?'DEMO':state.status==='PAUSED'?'PAUSED':state.status;
  return <div className="app-shell"><header className="telemetry-header"><div className="brand"><span>APEX</span><div><b>PIT WALL</b><small>F1 RACE MONITOR</small></div></div><div className="header-telemetry"><div><small>UDP LINK</small><b className={`link ${state.status.toLowerCase()}`}><i/>{statusLabel}</b><em>{age===null?'—':`${age}ms`} · {state.telemetry.packetsPerSecond}/s</em></div><div><small>LAP</small><b>{state.lap || '—'}<i> / {state.totalLaps || '—'}</i></b></div><div><small>FLAG</small><b className={`flag ${state.flag.toLowerCase()}`}>{state.flag}</b></div><div><small>TRACK</small><b>{state.context.trackTemp || '—'}°C</b><em>AIR {state.context.airTemp || '—'}°C</em></div></div><button className={`radio-pill ${radio.armed?'on':''} ${radio.status.toLowerCase()}`} onClick={radio.toggle} disabled={!radio.supported}>{radio.armed?<Volume2/>:<VolumeX/>}<span>{radio.armed?radio.status:'RADIO OFF'}</span></button></header><aside className="app-nav"><div className="nav-led"><Radio/></div>{nav.map(([to,label,Icon])=><NavLink key={to} to={to} end={to==='/' }><Icon/><span>{label}</span></NavLink>)}</aside><main className="workspace"><section className="context-bar"><div><span>{contextName(state.context.category)}</span><h1>{state.track}</h1></div><div className="context-meta"><span>{state.sessionType}</span><span>{state.weather}</span><strong>{timed?<>TIME {Math.floor(state.context.timeLeft/60)}:{String(state.context.timeLeft%60).padStart(2,'0')}</>:<>LAP {state.lap} / {state.totalLaps||'—'}</>}</strong></div></section><Routes><Route path="/" element={<RacePage s={state}/>}/><Route path="/timing" element={<TimingPage s={state}/>}/><Route path="/tyres" element={<Navigate to="/car" replace/>}/><Route path="/car" element={<CarPage s={state}/>}/><Route path="/analysis" element={<AnalysisPage s={state}/>}/><Route path="/sessions" element={<Navigate to="/analysis" replace/>}/><Route path="/settings" element={<SettingsPage radio={radio}/>}/></Routes></main></div>;
}
