import '@fontsource/barlow-condensed/latin-500.css';
import '@fontsource/barlow-condensed/latin-600.css';
import '@fontsource/barlow-condensed/latin-700.css';
import '@fontsource/barlow-condensed/latin-800.css';
import '@fontsource/inter/latin-400.css';
import '@fontsource/inter/latin-500.css';
import '@fontsource/inter/latin-600.css';
import '@fontsource/inter/latin-700.css';
import '@fontsource/jetbrains-mono/latin-500.css';
import '@fontsource/jetbrains-mono/latin-600.css';
import '@fontsource/jetbrains-mono/latin-700.css';
import { ErrorBoundary } from './ErrorBoundary';
import { AuthGate } from './AuthGate';
import React from 'react';import{createRoot}from'react-dom/client';import{BrowserRouter}from'react-router-dom';import'./styles-v25.css';import{App}from'./App-v25';
createRoot(document.getElementById('root')!).render(<React.StrictMode><BrowserRouter><ErrorBoundary><AuthGate><App/></AuthGate></ErrorBoundary></BrowserRouter></React.StrictMode>);
