import test from 'node:test';
import assert from 'node:assert/strict';
import { initialState } from '../server/state.js';
import { radioEnglishText, radioText, selectRadioMessage } from './radioLogic';

test('radio selects an actionable engineer call over coaching',()=>{const state=initialState(),now=1000;state.coach.message={id:'coach-brake-3-2',priority:'info',title:'BRAKE LATER · CORNER 3',evidence:'Repeated.',action:'Brake later.',confidence:80,createdAt:now,expiresAt:now+5000};state.engineer.primary={id:'strategy-undercut',priority:'opportunity',title:'UNDERCUT AVAILABLE',evidence:'Gap.',action:'Box.',confidence:90,createdAt:now,expiresAt:now+5000};assert.equal(selectRadioMessage(state)?.id,'strategy-undercut');assert.match(radioText(state.engineer.primary,state),/Undercut/)});
test('radio translates coaching into a short Spanish instruction',()=>{const state=initialState(),message={id:'coach-brake-4-8',priority:'info' as const,title:'BRAKE LATER · CORNER 4',evidence:'Repeated.',action:'Brake later.',confidence:80,createdAt:1000,expiresAt:6000};assert.equal(radioText(message,state),'Curva 4. Probá frenar un poco más tarde.')});
test('radio has matching concise English text when no Spanish voice exists',()=>{const message={id:'strategy-undercut',priority:'opportunity' as const,title:'UNDERCUT AVAILABLE',evidence:'Gap.',action:'Box before the car ahead.',confidence:90,createdAt:1000,expiresAt:6000};assert.equal(radioEnglishText(message),'UNDERCUT AVAILABLE. Box before the car ahead.')});
test('radio speaks catch predictions and overcut calls in Spanish',()=>{const state=initialState(),now=1000;state.strategy.ahead={name:'NORRIS',position:1,gap:2,rate:-.5,direction:'GAINING',laps:4,catchLaps:4,tyre:'MEDIUM',tyreAge:8,pit:false};const prediction={id:'prediction-ahead-NORRIS-4',priority:'opportunity' as const,title:'CATCH IN 4 LAPS',evidence:'Trend.',action:'Prepare.',confidence:90,createdAt:now,expiresAt:6000};assert.match(radioText(prediction,state),/4 vueltas/);assert.match(radioText({...prediction,id:'strategy-overcut'},state),/Overcut/)});
test('radio explains mandatory strategy and post-pit push in Spanish',()=>{const state=initialState(),now=1000,message={id:'strategy-box-mandatory',priority:'action' as const,title:'BOX THIS LAP',evidence:'Required.',action:'Box.',confidence:98,createdAt:now,expiresAt:6000};assert.match(radioText(message,state),/cambiar de compuesto/);state.strategy.lastStop={pitLap:7,exitLap:8,entryPosition:1,exitPosition:6,predictedMin:5,predictedMax:7,actualLossSeconds:24.9,positionsRecovered:0,cycleComplete:false};assert.match(radioText({...message,id:'strategy-pit-exit-7'},state),/posición 6/);});
test('radio uses short human final-lap and finish messages',()=>{const state=initialState(),now=1000,message={id:'final-lap',priority:'action' as const,title:'FINAL LAP',evidence:'P2.',action:'Bring it home.',confidence:100,createdAt:now,expiresAt:6000};state.player.position=2;state.sessionSummary={status:'FINISHED',finalPosition:2,startPosition:5,positionsGained:3,bestLap:'1:30.000',stops:1,compounds:['MEDIUM','SOFT'],incidents:0,damage:[]};assert.match(radioText(message,state),/Última vuelta/);assert.match(radioText({...message,id:'race-finished'},state),/Ganaste 3 posiciones/);});
test('radio pluralizes a one-lap catch correctly',()=>{const state=initialState(),now=1000;state.strategy.ahead={name:'NORRIS',position:1,gap:.4,rate:-.4,direction:'GAINING',laps:4,catchLaps:1,tyre:'MEDIUM',tyreAge:8,pit:false};const message={id:'prediction-ahead-0-2',priority:'opportunity' as const,title:'CATCH IN 1 LAP',evidence:'Trend.',action:'Attack.',confidence:90,createdAt:now,expiresAt:6000};assert.match(radioText(message,state),/1 vuelta\./);});
